// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Web.Data.ViewModels
{
    public partial class EmsTblAcademicQualificationVM
    {
        public int EtaqAqId { get; set; }
        public int? EtaqEtedEmployeeId { get; set; }
        public string EtaqQualification { get; set; }
        public long EtaqPassingYear { get; set; }
        public double? EtaqCgpa { get; set; }
        public string EtaqInstituteName { get; set; }
        public string EtaqUploadDocuments { get; set; }
        public string EtaqCreatedBy { get; set; }
        public string EtaqCreatedByName { get; set; }
        public DateTime? EtaqCreatedByDate { get; set; }
        public string EtaqModifiedBy { get; set; }
        public string EtaqModifiedByName { get; set; }
        public DateTime? EtaqModifiedByDate { get; set; }
        public bool? EtaqIsDelete { get; set; }
        [JsonIgnore]
        public virtual EmsTblEmployeeDetailsVM EtaqEtedEmployeeVM { get; set; }
    }
}