// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Web.Data.ViewModels
{
    public partial class ImsAssetsCategoryVM
    {
     
        public int ItacCategoryId { get; set; }
        public string ItacCategoryName { get; set; }
        public string ItacCreatedBy { get; set; }
        public string ItacCreatedByName { get; set; }
        public DateTime? ItacCreatedByDate { get; set; }
        public string ItacModifiedBy { get; set; }
        public string ItacModifiedByName { get; set; }
        public DateTime? ItacModifiedByDate { get; set; }
        public bool? ItacIsDelete { get; set; }

        public List<ImsAssetsVM> ImsAssets { get; set; }
        public List<ImsAssignVM> ImsAssign { get; set; }
    }
}