// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.API
{
    public partial class HrmsDropdown
    {
        public HrmsDropdown()
        {
            HrmsDropdownValue = new HashSet<HrmsDropdownValue>();
        }

        public int HdDropdownId { get; set; }
        public string HdDropdownName { get; set; }
        public string HdCreatedBy { get; set; }
        public string HdCreatedByName { get; set; }
        public DateTime? HdCreatedByDate { get; set; }
        public bool? HdIsDelete { get; set; }

        public virtual ICollection<HrmsDropdownValue> HrmsDropdownValue { get; set; }
    }
}