// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.API
{
    public partial class ImsAssetsCategory
    {
        public ImsAssetsCategory()
        {
            ImsAssets = new HashSet<ImsAssets>();
            ImsAssign = new HashSet<ImsAssign>();
        }

        public int ItacCategoryId { get; set; }
        public string ItacCategoryName { get; set; }
        public string ItacCreatedBy { get; set; }
        public string ItacCreatedByName { get; set; }
        public DateTime? ItacCreatedByDate { get; set; }
        public string ItacModifiedBy { get; set; }
        public string ItacModifiedByName { get; set; }
        public DateTime? ItacModifiedByDate { get; set; }
        public bool? ItacIsDelete { get; set; }

        public virtual ICollection<ImsAssets> ImsAssets { get; set; }
        public virtual ICollection<ImsAssign> ImsAssign { get; set; }
    }
}