// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.API
{
    public partial class LmsLeaveRecord
    {
        public int LmslrRecordId { get; set; }
        public int? LmslrEtedEmployeeId { get; set; }
        public int? LmslrAnnualAssign { get; set; }
        public int? LmslrSickAssign { get; set; }
        public int? LmslrCasualAssign { get; set; }
        public int? LmslrTotalAssign { get; set; }
        public int? LmslrAnnualTaken { get; set; }
        public int? LmslrSickTaken { get; set; }
        public int? LmslrCasualTaken { get; set; }
        public int? LmslrTotalTaken { get; set; }
        public string LmslrCreatedBy { get; set; }
        public string LmslrCreatedByName { get; set; }
        public DateTime? LmslrCreatedByDate { get; set; }
        public bool? LmslrIsDelete { get; set; }

        public virtual EmsTblEmployeeDetails LmslrEtedEmployee { get; set; }
    }
}