// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.API
{
    public partial class LmsLeaveType
    {
        public LmsLeaveType()
        {
            LmsEmployeeLeave = new HashSet<LmsEmployeeLeave>();
        }

        public int LmsltTypeId { get; set; }
        public string LmsltLeaveName { get; set; }
        public string LmsltCreatedBy { get; set; }
        public string LmsltCreatedByName { get; set; }
        public DateTime? LmsltCreatedByDate { get; set; }
        public bool? LmsltIsDelete { get; set; }

        public virtual ICollection<LmsEmployeeLeave> LmsEmployeeLeave { get; set; }
    }
}