// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Data.Models
{
    public partial class EmsCategoryStatus
    {
        public EmsCategoryStatus()
        {
            EmsEmployementStatus = new HashSet<EmsEmployementStatus>();
            EmsTblEmployeeProfessionalDetails = new HashSet<EmsTblEmployeeProfessionalDetails>();
        }

        public int EcsStatusId { get; set; }
        public string EcsStatusName { get; set; }
        public string EcsCreatedBy { get; set; }
        public string EcsCreatedByName { get; set; }
        public DateTime? EcsCreatedByDate { get; set; }
        public bool? EcsIsDelete { get; set; }

        public virtual ICollection<EmsEmployementStatus> EmsEmployementStatus { get; set; }
        public virtual ICollection<EmsTblEmployeeProfessionalDetails> EmsTblEmployeeProfessionalDetails { get; set; }
    }
}