// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Data.Models
{
    public partial class EmsEmployementStatus
    {
        public int EesEmployementId { get; set; }
        public int EesEtedEmployeeId { get; set; }
        public int EesEcsEmpstatusId { get; set; }
        public DateTime? EesStartDate { get; set; }
        public DateTime? EesEndDate { get; set; }
        public int? EesIncrement { get; set; }
        public string EesRemarks { get; set; }
        public string EesDuration { get; set; }
        public int EesSalary { get; set; }
        public string EesCreatedBy { get; set; }
        public string EesCreatedByName { get; set; }
        public DateTime? EesCreatedByDate { get; set; }
        public string EesModifiedBy { get; set; }
        public string EesModifiedByName { get; set; }
        public DateTime? EesModifiedByDate { get; set; }
        public bool? EesIsDelete { get; set; }
        public int? Monday { get; set; }
        public int? Tuesday { get; set; }
        public int? Wednesday { get; set; }
        public int? Thrusday { get; set; }
        public int? Friday { get; set; }
        public int? EesEtedParttimeType { get; set; }
        public DateTime? EesDateOfIncrement { get; set; }
        public int? EesContractType { get; set; }
        public string EesClearenceDate { get; set; }
        public string EesEvaluationDate { get; set; }
        public string EesReleasingDate { get; set; }

        public virtual EmsCategoryStatus EesEcsEmpstatus { get; set; }
        public virtual EmsTblEmployeeDetails EesEcsEmpstatusNavigation { get; set; }
    }
}