// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Data.Models
{
    public partial class EmsTblEmployeeProfessionalDetails
    {
        public int EtepdPdId { get; set; }
        public int? EtepdEtedEmployeeId { get; set; }
        public string EtepdDesignation { get; set; }
        public string EtepdSalary { get; set; }
        public DateTime? EtepdJoiningDate { get; set; }
        public string EtepdProbation { get; set; }
        public string EtepdCreatedBy { get; set; }
        public string EtepdCreatedByName { get; set; }
        public DateTime? EtepdCreatedByDate { get; set; }
        public string EtepdModifiedBy { get; set; }
        public string EtepdModifiedByName { get; set; }
        public DateTime? EtepdModifiedByDate { get; set; }
        public bool? EtepdIsDelete { get; set; }
        public int? EtepdEcsStatusId { get; set; }

        public virtual EmsCategoryStatus EtepdEcsStatus { get; set; }
        public virtual EmsTblEmployeeDetails EtepdEtedEmployee { get; set; }
    }
}