// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Data.Models
{
    public partial class EmsTblProfessionalQualification
    {
        public int EtpqPqId { get; set; }
        public int? EtpqEtedEmployeeId { get; set; }
        public string EtpqCertification { get; set; }
        public DateTime? EtpqStratDate { get; set; }
        public DateTime? EtpqEndDate { get; set; }
        public string EtpqInstituteName { get; set; }
        public string EtpqDocuments { get; set; }
        public string EtpqCreatedBy { get; set; }
        public string EtpqCreatedByName { get; set; }
        public DateTime? EtpqCreatedByDate { get; set; }
        public string EtpqModifiedBy { get; set; }
        public string EtpqModifiedByName { get; set; }
        public DateTime? EtpqModifiedByDate { get; set; }
        public bool? EtpqIsDelete { get; set; }

        public virtual EmsTblEmployeeDetails EtpqEtedEmployee { get; set; }
    }
}