// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Web.Data.Models
{
    public partial class ImsAssets
    {
        public ImsAssets()
        {
            ImsAc = new HashSet<ImsAc>();
            ImsCctvCameras = new HashSet<ImsCctvCameras>();
            ImsDrives = new HashSet<ImsDrives>();
            ImsFans = new HashSet<ImsFans>();
            ImsFurniture = new HashSet<ImsFurniture>();
            ImsKeyboard = new HashSet<ImsKeyboard>();
            ImsLaptop = new HashSet<ImsLaptop>();
            ImsMouse = new HashSet<ImsMouse>();
            ImsPowerCable = new HashSet<ImsPowerCable>();
            ImsPrinters = new HashSet<ImsPrinters>();
            ImsScreens = new HashSet<ImsScreens>();
            ImsStationery = new HashSet<ImsStationery>();
        }

        public int ItaAssetId { get; set; }
        public string ItaAssetName { get; set; }
        public int ItaQuantity { get; set; }
        public long ItaCost { get; set; }
        public DateTime ItaPurchaseDate { get; set; }
        public int ItaAssignedTo { get; set; }
        public string ItaCreatedBy { get; set; }
        public string ItaCreatedByName { get; set; }
        public DateTime? ItaCreatedByDate { get; set; }
        public string ItaModifiedBy { get; set; }
        public string ItaModifiedByName { get; set; }
        public DateTime? ItaModifiedByDate { get; set; }
        public bool? ItaIsDelete { get; set; }

        public virtual ICollection<ImsAc> ImsAc { get; set; }
        public virtual ICollection<ImsCctvCameras> ImsCctvCameras { get; set; }
        public virtual ICollection<ImsDrives> ImsDrives { get; set; }
        public virtual ICollection<ImsFans> ImsFans { get; set; }
        public virtual ICollection<ImsFurniture> ImsFurniture { get; set; }
        public virtual ICollection<ImsKeyboard> ImsKeyboard { get; set; }
        public virtual ICollection<ImsLaptop> ImsLaptop { get; set; }
        public virtual ICollection<ImsMouse> ImsMouse { get; set; }
        public virtual ICollection<ImsPowerCable> ImsPowerCable { get; set; }
        public virtual ICollection<ImsPrinters> ImsPrinters { get; set; }
        public virtual ICollection<ImsScreens> ImsScreens { get; set; }
        public virtual ICollection<ImsStationery> ImsStationery { get; set; }
    }
}