// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Web.Data.Models
{
    public partial class ImsCctvCameras
    {
        public int ItccCctvId { get; set; }
        public int? ItaAssetId { get; set; }
        public string ItccSerialNo { get; set; }
        public string ItccModelNo { get; set; }
        public string ItccPixels { get; set; }
        public string ItccCreatedBy { get; set; }
        public string ItccCreatedByName { get; set; }
        public DateTime? ItccCreatedByDate { get; set; }
        public string ItccModifiedBy { get; set; }
        public string ItccModifiedByName { get; set; }
        public DateTime? ItccModifiedByDate { get; set; }
        public bool? ItccIsDelete { get; set; }
        [JsonIgnore]
        public virtual ImsAssets ItaAsset { get; set; }
    }
}