// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Web.Data.Models
{
    public partial class ImsFans
    {
        public int ItfaFanId { get; set; }
        public int? ItaAssetId { get; set; }
        public string ItfaSerialNo { get; set; }
        public string ItfaModelNo { get; set; }
        public string ItfaType { get; set; }
        public string ItfaCreatedBy { get; set; }
        public string ItfaCreatedByName { get; set; }
        public DateTime? ItfaCreatedBy1 { get; set; }
        public string ItfaModifiedBy { get; set; }
        public string ItfaModifiedByName { get; set; }
        public DateTime? ItfaModifiedBy1 { get; set; }
        public bool? ItfaIsDelete { get; set; }
        [JsonIgnore]
        public virtual ImsAssets ItaAsset { get; set; }
    }
}