// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Web.Data.Models
{
    public partial class ImsFurniture
    {
        public int ItfFurnitureId { get; set; }
        public int? ItaAssetId { get; set; }
        public string ItfType { get; set; }
        public string ItfCreatedBy { get; set; }
        public string ItfCreatedByName { get; set; }
        public DateTime? ItfCreatedByDate { get; set; }
        public string ItfModifiedBy { get; set; }
        public string ItfModifiedByName { get; set; }
        public DateTime? ItfModifiedByDate { get; set; }
        public bool? ItfIsDelete { get; set; }
        [JsonIgnore]
        public virtual ImsAssets ItaAsset { get; set; }
    }
}