// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Web.Data.Models
{
    public partial class ImsKeyboard
    {
        public int ItkKeyboardId { get; set; }
        public int? ItaAssetId { get; set; }
        public string ItkModelNo { get; set; }
        public string ItkCompanyName { get; set; }
        public string ItkCreatedBy { get; set; }
        public string ItkCreatedByName { get; set; }
        public DateTime? ItkCreatedBy1 { get; set; }
        public string ItkModifiedBy { get; set; }
        public string ItkModifiedByName { get; set; }
        public DateTime? ItkModifiedBy1 { get; set; }
        public bool? ItkIsDelete { get; set; }
        [JsonIgnore]
        public virtual ImsAssets ItaAsset { get; set; }
    }
}