// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Web.Data.Models
{
    public partial class ImsLaptop
    {
        public int ItlLaptopId { get; set; }
        public int? ItaAssetId { get; set; }
        public string ItlSerialNo { get; set; }
        public string ItlGeneration { get; set; }
        public string ItlRam { get; set; }
        public string ItlProcessor { get; set; }
        public string ItlHdd { get; set; }
        public string ItlCompanyName { get; set; }
        public string ItlCreatedBy { get; set; }
        public string ItlCreatedByName { get; set; }
        public DateTime? IltCreatedByDate { get; set; }
        public string ItlModifiedBy { get; set; }
        public string ItlModifiedByName { get; set; }
        public DateTime? ItlModifiedByDate { get; set; }
        public bool? ItlIsDelete { get; set; }
        [JsonIgnore]
        public virtual ImsAssets ItaAsset { get; set; }
    }
}