// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Web.Data.Models
{
    public partial class ImsPrinters
    {
        public int ItpPrinterId { get; set; }
        public int? ItaAssetId { get; set; }
        public string ItpModelNo { get; set; }
        public string ItpCompanyName { get; set; }
        public string ItpType { get; set; }
        public string ItpCreatedBy { get; set; }
        public string ItpCreatedByName { get; set; }
        public DateTime? ItpCreatedByDate { get; set; }
        public string ItpModifiedBy { get; set; }
        public string ItpModifiedByName { get; set; }
        public DateTime? ItpModifiedByDate { get; set; }
        public bool? ItpIsDelete { get; set; }
        [JsonIgnore]
        public virtual ImsAssets ItaAsset { get; set; }
    }
}