// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Web.Data.Models
{
    public partial class ImsPowerCable
    {
        public int ItpcPowerId { get; set; }
        public int? ItaAssetId { get; set; }
        public string ItpcCreatedBy { get; set; }
        public string ItpcCreatedByName { get; set; }
        public DateTime? ItpcCreatedBy1 { get; set; }
        public string ItpcModifiedBy { get; set; }
        public string ItpcModifiedByName { get; set; }
        public DateTime? ItpcModifiedBy1 { get; set; }
        public bool? ItpcIsDelete { get; set; }
        [JsonIgnore]
        public virtual ImsAssets ItaAsset { get; set; }
    }
}