// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Web.Data.Models
{
    public partial class ImsStationery
    {
        public int ItsStationeryId { get; set; }
        public int? ItaAssetId { get; set; }
        public string ItsType { get; set; }
        public string ItsCreatedBy { get; set; }
        public string ItsCreatedByName { get; set; }
        public DateTime? ItsCreatedByDate { get; set; }
        public string ItsModifiedBy { get; set; }
        public string ItsModifiedByName { get; set; }
        public DateTime? ItsModifiedByDate { get; set; }
        public bool? ItsIsDelete { get; set; }
        [JsonIgnore]
        public virtual ImsAssets ItaAsset { get; set; }
    }
}