// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Web.Data.Models
{
    public partial class ImsScreens
    {
        public int ItscScreenId { get; set; }
        public int? ItaAssetId { get; set; }
        public string ItscModelNo { get; set; }
        public string ItscCompanyName { get; set; }
        public string ItscSize { get; set; }
        public string ItscCreatedBy { get; set; }
        public string ItscCreatedByName { get; set; }
        public DateTime? ItscCreatedBy1 { get; set; }
        public string ItscModifiedBy { get; set; }
        public string ItscModifiedByName { get; set; }
        public DateTime? ItscModifiedBy1 { get; set; }
        public bool? ItscIsDelete { get; set; }
        [JsonIgnore]
        public virtual ImsAssets ItaAsset { get; set; }
    }
}