// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace Web.Data.Models
{
    public partial class ImsTblAssign
    {
        public int ItasAssignId { get; set; }
        public string ItasAssetName { get; set; }
        public int ItasAssetIdFk { get; set; }
        public int? ItasQuantity { get; set; }
        public int ItasAssignedToId { get; set; }
        public string ItasAssignedToName { get; set; }
        public string ItasCreatedBy { get; set; }
        public string ItasCreatedByName { get; set; }
        public DateTime? ItasCreatedByDate { get; set; }
        public string ItasModifiedBy { get; set; }
        public string ItasModifiedByName { get; set; }
        public DateTime? ItasModifiedByDate { get; set; }
        public bool? ItasIsDelete { get; set; }
        [JsonIgnore]
        public virtual ImsTblAssets ItasAssetIdFkNavigation { get; set; }
        [JsonIgnore]
        public virtual EmsTblEmployeeDetails ItasAssignedTo { get; set; }
    }
}