// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Data.Models
{
    public partial class RmsTblPositionApplied
    {
        public RmsTblPositionApplied()
        {
            RmsTblRecruiter = new HashSet<RmsTblRecruiter>();
        }

        public int RtpaPosId { get; set; }
        public string RtpaPosition { get; set; }
        public string RtpaCreatedBy { get; set; }
        public string RtpaCreatedByName { get; set; }
        public DateTime? RtpaCreatedByDate { get; set; }
        public string RtpaModifiedBy { get; set; }
        public string RtpaModifiedByName { get; set; }
        public DateTime? RtpaModifiedByDate { get; set; }
        public bool? RtpaIsDelete { get; set; }

        public virtual ICollection<RmsTblRecruiter> RmsTblRecruiter { get; set; }
    }
}